version: '3.7'

services:
    mongodb:
        image: mongo:4.4.14
        container_name: mongodb_bs
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
            MONGO_INITDB_DATABASE: BeatSaber
        ports:
            - 27017:27017
        volumes:
            - ./Database/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro